services:
  redis:
    image: redis:latest
    container_name: redis-wwebjs
    ports:
      - "127.0.0.1:6379:6379"  # נגיש רק ל-localhost
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - internal-net  # רשת משותפת

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-cluster
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
    depends_on:
      - redis
      - postgres  # Add dependency on PostgreSQL
    environment:
      - REDIS_HOST=redis  # חשוב: השם הזה הוא שם הקונטיינר
      - REDIS_PORT=6379
      - DB_HOST=postgres  # PostgreSQL container name
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=whatsapp
    restart: always
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./session_logs:/usr/src/app/session_logs
    networks:
      - internal-net  # גם כאן

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "127.0.0.1:5432:5432"  # Access PostgreSQL from localhost
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatsapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal-net  # Same network

volumes:
  redis_data:
    driver: local
  postgres_data:  # Volume for PostgreSQL data
    driver: local
  whatsapp_sessions:
    driver: local

networks:
  internal-net:
    driver: bridge