services:
  redis:
    image: redis:latest
    container_name: redis-wwebjs
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - internal-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-cluster
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsapp-cluster.rule=Host(`api.elhanan.org`)"
      - "traefik.http.routers.whatsapp-cluster.entrypoints=websecure"
      - "traefik.http.routers.whatsapp-cluster.tls.certresolver=myresolver"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=whatsapp
    restart: always
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./session_logs:/usr/src/app/session_logs
    networks:
      - internal-net

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatsapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal-net

  reverse-proxy:
    image: traefik:v3.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=elhanan@elhanan.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - internal-net

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  whatsapp_sessions:
    driver: local
  letsencrypt:
    driver: local

networks:
  internal-net:
    driver: bridge
