name: Deploy to AWS Lightsail

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 52.59.248.51 >> ~/.ssh/known_hosts
      
      - name: Deploy to Lightsail
        run: |
          ssh ubuntu@52.59.248.51 "cd ~/wwebjs-server && \
            git pull && \
            # Fix permissions on WhatsApp session directories
            sudo chmod -R 777 whatsapp-session || true && \
            # Alternative command if the above doesn't work
            # sudo chown -R ubuntu:ubuntu whatsapp-session || true && \
            docker-compose down && \
            docker-compose build --no-cache && \
            docker-compose up -d"