name: Deploy to contabo server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 31.220.95.51 >> ~/.ssh/known_hosts
      - name: Deploy to Contabo VPS
        run: |
          ssh root@31.220.95.51 "cd ~/wwebjs-server && \
            git pull && \
            sudo chmod -R 777 whatsapp-session || true && \
            docker-compose down && \
            docker-compose build --no-cache && \
            docker-compose up -d"
        shell: /bin/bash -e {0}